DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS nodes;

CREATE TABLE nodes(
    id BIGINT NOT NULL PRIMARY KEY,
    lon DOUBLE PRECISION NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    username VARCHAR(256) NOT NULL
--     uid BIGINT NOT NULL,
--     visible BOOLEAN NOT NULL,
--     version INT NOT NULL,
--     changelist BIGINT NOT NULL
);

CREATE TABLE tags(
    node_id BIGINT NOT NULL REFERENCES nodes(id),
    key VARCHAR(256) NOT NULL,
    value VARCHAR(256) NOT NULL,
    PRIMARY KEY (node_id, key)
);